### ISSUE TITLE
regular expression filter operator for selecting features

### ISSUE THREAD

**Issue by clkao** [mapbox/DEPRECATED-mapbox-gl#20] opened 2016-07-04 14:14 UTC
Perhaps something like:

```
["match", "iso_3166_2", "^TW.*"]
["!match", "shield", "^us-*"]
```

**Comment by tmcw** [comment] 2016-07-04 15:45
Thanks for the suggestion! This is a duplicate of the existing [issue in the style-spec repo](https://github.com/mapbox/mapbox-gl-style-spec/issues/233), so closing to consolidate.

**Closed as completed by tmcw** 2016-07-04 15:45 UTC
